### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by RyanZim** [rocktemplates/rock#14]
@jprichardson It seems that you're using submodules for `test/resources/rocks/node-lib`, however there is no `.gitmodules` file. Not sure what is going on here. Advice?

**Comment by jprichardson** [comment]
That's weird, because I don't recall using submodules in this project... maybe just remove it?

**Comment by RyanZim** [comment]
I suspect you accidentally copied the `.git` directory when you added `node-lib`. I removed it and re-added the correct contents in PR #15.
