### ISSUE TITLE
.git directory when rock is local path

### ISSUE THREAD

**Issue by RyanZim** [rocktemplates/rock#19]
When the rock is a local git repo, rock attempts to copy the `.git` directory. This can result in:

```
Error: EACCES: permission denied, open '/home/ryan/t-rock/.git/objects/1f/ee00ff92c39ec7511ec2309916d9a05eb01ace'
    at Error (native)
```

Not to mention that copying the `.git` directory is counter-intuitive IMO.

Perhaps use `copy()` with the `filter` option?

_This would be a breaking change._

**Comment by jprichardson** [comment]
> Not to mention that copying the .git directory is counter-intuitive IMO.

Agreed!

> This would be a breaking change.

That's ok, if that's how we gotta make progress, so be it! :)

**Comment by RyanZim** [comment]
> That's ok, if that's how we gotta make progress, so be it! :)

Love that attitude! :grinning:
