### ISSUE TITLE
Empty Directories in Rocks

### ISSUE THREAD

**Issue by RyanZim** [rocktemplates/rock#22]
Git doesn't track empty directories, so I can't get rock to initialize empty directories.

@jprichardson Thoughts on workarounds?

# Proposal 1

Allow a `delete` array to `.rock/rock.json` for an array of file/directory globs to delete when rock has finished.

Then you could:

1. Add a dummy file `.delete` in each empty directory.
1. Add `**/.delete` to the `delete` array in `.rock/rock.json`.

Git would track the `.delete` files and rock would remove them. _Profit!_

**Comment by jprichardson** [comment]
I think either using `.delete` is fine. A Git standard convention is to drop a `.gitkeep` in a directory.

**Comment by jprichardson** [comment]
I'm good with which ever you'd like.

**Comment by RyanZim** [comment]
OK, never heard of `.gitkeep`. I'll implement a `delete` array as soon as I get to it.
