### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by RyanZim** [rocktemplates/rock#25]
@jprichardson It would greatly simplify testing if we did two things:

- Remove all instances of `date` from the test rocks and tested that separately against a dynamically generated string. (So the tests don't break when the year changes)
- Test the github download against a separate, minimal repo instead of https://github.com/rocktemplates/node-lib. We should keep the test repo as small as possible, so that we don't have to change it very often. It should contain:
  - A README that is not used in unit testing, that way it can be updated without breaking tests.
  - A file used for testing with the contents of:
  
  ```
  Hello {{ name }}!
  ```

I am working on the first point, and will implement the second as soon as you make the repo.

**Comment by jprichardson** [comment]
> , and will implement the second as soon as you make the repo.

Sorry, you should be able to add, edit, delete repos now.

**Comment by RyanZim** [comment]
OK, Thanks!
